name: text_wallpaper
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  google_fonts: ^6.1.0
  screenshot: ^3.0.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  gal: ^2.1.0
  uuid: ^4.2.1
  wallpaper_manager_plus: ^2.0.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  launcher_name: ^1.0.2 
  icons_launcher: ^3.0.3
  change_app_package_name: ^1.4.0

launcher_name:
  default: "BrainPaper" 
  bn: "ব্রেইন পেপার"

icons_launcher:
  image_path: "assets/logo/logo_black.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:
  uses-material-design: true